#!/bin/sh
echo $PWD
foot -d none sh -c "cd "$PWD" && nnn" &


export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd";if [ -f "$NNN_TMPFILE" ]; then; . "$NNN_TMPFILE"; rm -f "$NNN_TMPFILE" > /dev/null; fi

