# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix") ];

	boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-intel" ];
	boot.extraModulePackages = [ config.boot.kernelPackages.v4l2loopback ];
	swapDevices = [{device = "/data/.state/swapfile";}];

	boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

	powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

	# Hardware acceleration
	#hardware.opengl = {
	#	enable = true;
	#	driSupport = true;
	#	extraPackages = with pkgs; [ intel-media-driver libva ];
	#};

	#environment.variables = rec {
	#	LIBVA_DRIVER_NAME = "iHD";
	#};
}
